import { NextRequest, NextResponse } from 'next/server';
import { redis } from '@/src/utils/redis';
import crypto from 'crypto';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

function validateSignature(userId: string, timestamp: string, signature: string): boolean {
  const secret = process.env.ENCRYPTION_KEY || process.env.CRON_SECRET;
  if (!secret) return false;

  const age = Date.now() - parseInt(timestamp);
  if (isNaN(age) || age > 3600_000) return false;

  const expected = crypto.createHmac('sha256', secret).update(`${userId}:${timestamp}`).digest('hex');
  return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature));
}

/**
 * GET /api/weather-image?user_id=X&ts=TIMESTAMP&sig=SIGNATURE
 * Serves pre-rendered weather infographic from Redis cache.
 * Image is pre-generated by /api/weather-image/sign.
 */
export async function GET(request: NextRequest) {
  const userId = request.nextUrl.searchParams.get('user_id');
  const ts = request.nextUrl.searchParams.get('ts');
  const sig = request.nextUrl.searchParams.get('sig');

  if (!userId || !ts || !sig) {
    return NextResponse.json({ error: 'Missing parameters' }, { status: 400 });
  }

  if (!validateSignature(userId, ts, sig)) {
    return NextResponse.json({ error: 'Invalid or expired signature' }, { status: 401 });
  }

  // Serve from Redis cache (pre-rendered by /sign endpoint)
  const cacheKey = `story:img:${userId}`;
  const cached = await redis.get<string>(cacheKey);

  if (!cached) {
    return NextResponse.json({ error: 'Image not found — try again' }, { status: 404 });
  }

  const imageBuffer = Buffer.from(cached, 'base64');

  return new NextResponse(new Uint8Array(imageBuffer), {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=1800',
    },
  });
}
